apiVersion: v1
kind: ServiceAccount
metadata:
  name: bmh-reader-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmh-reader
rules:
- apiGroups: ["metal3.io"]
  resources: ["baremetalhosts"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bmh-reader-cr-binding
subjects:
  - kind: ServiceAccount
    name: bmh-reader-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: bmh-reader
  apiGroup: rbac.authorization.k8s.io
